version: '2'

services:
  simulator:
    image: ros2dev:v3
    # network_mode: "host"
    devices:
      - "/dev/dri"
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: gazebo --verbose /ros_dev/model.world
  commander:
    image: ros2dev:v3
    # network_mode: "host"
    command: "ros2 topic pub /demo/cmd_demo geometry_msgs/Twist '{linear: {x: 1.0}}' -1"
    depends_on:
      - simulator